Update veracode-policy-scan.yml

diff --git a/.github/workflows/veracode-policy-scan.yml b/.github/workflows/veracode-policy-scan.yml
--- a/.github/workflows/veracode-policy-scan.yml
+++ b/.github/workflows/veracode-policy-scan.yml
@@ -130,13 +130,27 @@ jobs:
         with:
           name: policy-flaws
           path: /tmp
-
+          
+      - name: Checkout Target Repository
+        uses: actions/checkout@v4
+        with:
+          repository: AccionQA/QuatarFlaws
+          token: ${{ inputs.token }}
+          path: target-repo
+          
+      - name: Check if policy_flaws.json exists
+        run: |
+         if [ ! -f target-repo/policy_flaws.json ]; then
+         echo "Error: policy_flaws.json file not found in target-repo."
+         exit 1
+         fi   
+         
       - name: Convert policy scan output to SARIF format for java language
         if: ${{ inputs.language == 'Java' }}
-        uses: Veracode/veracode-pipeline-scan-results-to-sarif@v2.0.3
+        uses: Veracode/veracode-pipeline-scan-results-to-sarif@master
         with:
           scan-type: policy
-          results-json: '/tmp/policy_flaws.json'
+          results-json: 'target-repo/policy_flaws.json'
           output-results-sarif: veracode-results.sarif
           repo_owner: ${{ inputs.owner }}
           repo_name: ${{ inputs.repo }}
